FROM arm64v8/golang:1.20 as golang

FROM arm64v8/python:3.9-bullseye

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install scons patchelf libnss3-dev -y

COPY --from=golang /usr/local/go /usr/local/go
ENV PATH="${PATH}:/usr/local/go/bin"

ENTRYPOINT /bin/bash