name: Continuous Integration

on:
  push:
    branches: [arm-support]
    paths-ignore:
      - 'README.md'

env:
  PYTHON_DEFAULT_VERSION: '3.9'
  GO_DEFAULT_VERSION: '1.20'

jobs:
  build-linux-arm64-pybindings:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v3
      - name: Build python bindings
        working-directory: python-bindings
        run: |
          docker run -it --rm --platform linux/arm64 -v .:/work arm64v8/python:3.9-bulleye /bin/bash -c "apt-get update -y && apt-get install scons patchelf libnss3-dev -y && cd /work && make deps && make build"
      - name: Upload python bindings
        with:
          name: py-terraform-provider-b2-linux
          path: python-bindings/dist/py-terraform-provider-b2
          if-no-files-found: error
          retention-days: 1