name: Continuous Integration

on:
  push:
    branches: [arm-support]
    paths-ignore:
      - 'README.md'

env:
  PYTHON_DEFAULT_VERSION: '3.9'
  GO_DEFAULT_VERSION: '1.20'

jobs:
  build-linux-arm64-pybindings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pguyot/arm-runner-action@v2
        with:
          commands: |
            sudo apt-get update -y
            sudo apt-get upgrade -y
            sudo apt-get install -y scons patchelf libnss3-dev git build-essential lzma-dev liblzma-dev
            sudo apt-get install fd-find
            findfd libnss /
            # ln -s /usr/lib/aarch64-linux-gnu/libnss_files.so.2 /usr/lib/aarch64-linux-gnu/libnss_files.so
            # ln -s /usr/lib/aarch64-linux-gnu/libnss_dns.so.2 /usr/lib/aarch64-linux-gnu/libnss_dns.so

            pushd /root
            wget https://go.dev/dl/go1.20.12.linux-arm64.tar.gz
            tar xf go1.20.12.linux-arm64.tar.gz
            mv go /go
            wget https://www.python.org/ftp/python/3.9.18/Python-3.9.18.tar.xz
            tar -xf Python-3.9.18.tar.xz
            mv Python-3.9.18 /usr/local/share/python3.9
            pushd /usr/local/share/python3.9
            export PATH="${PATH}:/go/bin"
            ./configure --enable-optimizations --enable-shared
            make -j 7
            make altinstall
            ldconfig /usr/local/share/python3.9
            python3.9 -m venv /venv
            source /venv/bin/activate
            popd
            popd

            make deps
            cd python-bindings
            make build
          copy_artifact_path: python-bindings/dist/py-terraform-provider-b2