name: Continuous Integration

on:
  push:
    branches: [arm-support]
    paths-ignore:
      - 'README.md'

env:
  PYTHON_DEFAULT_VERSION: '3.9'
  GO_DEFAULT_VERSION: '1.20'

jobs:
  build-linux-arm64-pybindings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pguyot/arm-runner-action@v2
      - name: Install dependencies
        working-directory: python-bindings
        run: |
          apt-get -y update
          apt-get -y install patchelf
          make deps
      - name: Build python bindings
        id: build
        working-directory: python-bindings
        run: |
          make build
      - name: Upload python bindings
        uses: actions/upload-artifact@v2
        with:
          name: py-terraform-provider-b2-linux-arm64
          path: python-bindings/dist/py-terraform-provider-b2
          if-no-files-found: error
          retention-days: 1